### ISSUE TITLE
Circular dependency on Windows

### ISSUE THREAD

**Issue by cdprete** [mdbootstrap/mdb-react-ui-kit#105]
Hi :)

I'm using the latest version of mdbreact (4.25.6) and I get a circular dependency on Windows:

```
Circular dependency detected 4026c28649d137ac0d29a3d28adc7dcd
  ↓ ../node_modules/mdbreact/dist/mdbreact.esm.js
  ↓ ../node_modules/mdbreact/dist/mdbreact.esm.js
```

The same was true when I was using the version 4.24.0.

**Comment by jakubchmura** [comment]
HI @CDPrete,

Try a new MDBReact version. Your problem probably was fixed.

**Comment by cdprete** [comment]
Hi @JakubChm,
I've tried with version 4.26.1 but I still have the same issue.

**Comment by jakubchmura** [comment]
I need to redirect you to the MDB Support forum. We answer there with higher priority than on GitHub.  Please describe there your problem with more details and paste a code sample. Then we will be able to help you with this problem.

**Comment by cdprete** [comment]
We fixed this from our side by excluding the node_modules from the set of scanned sources.
