### ISSUE TITLE
Can't resolve 'mdbreact'

### ISSUE THREAD

**Issue by benoitkopp** [mdbootstrap/mdb-react-ui-kit#8]
Hello,

When i try to import Button and Collapse, i get:

Import:
`import { Button, Collapse } from 'mdbreact';`

Error:
`Module not found: Can't resolve 'mdbreact' in 'C:\wamp64\www\bob-web\notice-cmi\src\components\Collapsable'`

I installed it with npm. Did i miss something ?

**Comment by carlgrimm** [comment]
I noticed in their project they used an alias that points to where the /src directory lives in the resolve section of the webpack config.

`  resolve: {
    alias: {
      mdbreact: path.resolve('./src/index')
    }
  },`

**Comment by juergengunz** [comment]
@carlgrimm so what is the solution ? I don't get it. same issue for me

**Comment by carlgrimm** [comment]
One way is to get an alias into the resolve config section of your webpack configuration file if you are using webpack to build.

This repo builds the docs site using webpack and you can see in their configuration file that they create a resolve alias that maps mdbreact to the components they export in /src/index.js which fixes this en-mass for all of the components.

it also appears that the git repo might be out of sync with NPM package. The git repo has an index.js file that helps load everything that seems to be missing when you add from NPM.

**Comment by hunterdt** [comment]
I'm having the same problem. I tried installing from NPM and from Github download, but couldn't get it to work. 

Anyone find out exactly what needs to be done to solve this?

**Comment by mattonit** [comment]
It's fixed in 4.1.0

**Comment by hiqbalmallick** [comment]
@mattonit it's not fixed..still i'm getting this issue..please help me to solve it..

**Comment by mattonit** [comment]
what's your version of React?

**Comment by hiqbalmallick** [comment]
Version 4.1.0

Sent from my Windows Phone 

-----Original Message-----

**Comment by hiqbalmallick** [comment]
16.2.0

**Comment by smolenski-mikolaj** [comment]
Hello,
This error which could be connected with the latest upgrade of React. We've fixed it by updating our product to the latest React version. Please delete 'mdbreact' from package.json, reinstall and then add to dependencies this line:

"mdbreact":"git+https://github.com/mdbootstrap/React-Bootstrap-with-Material-Design.git#react-upgrade"

Let us know if it works properly.

Regards

**Comment by hiqbalmallick** [comment]
still not working..

**Comment by hiqbalmallick** [comment]
its giving multiple errors now..jquery not defined..when i'm trying to test by copying the navbar code..'navbar' has no owner...such things..

**Comment by smolenski-mikolaj** [comment]
Please build a new React App and check our mdbreact with it. It's not possible to see jquery errors because it's not working with jquery, but with plain js. If it's still not working please write what are Your steps to create this App.

**Comment by hiqbalmallick** [comment]
I created a new project through:
create-react-app myproject
Then after installation..i ran the command:
npm install --save mdbreact
And when i copied the code of navbar for testing purpose..it gave me that error..did i miss something?

Sent from my Windows Phone 

-----Original Message-----

**Comment by iainalba** [comment]
Is there a fix for this? I'm having the same issue

**Comment by hiqbalmallick** [comment]
Haven't found yet..

Sent from my Windows Phone 

-----Original Message-----

**Comment by vicks1008** [comment]
Having this same issue.

**Comment by eduardoroliveira** [comment]
I'm having the same error.

**Comment by benoitkopp** [comment]
Since new updates, it's working, which version do you use ?

**Comment by shogan94** [comment]
Can't use any components with version 4.8.2 and react version 16.6.0, is there a secret to how to import?

**Comment by benoitkopp** [comment]
Still importing like:

import { Button, Modal, ModalBody, ModalHeader } from 'mdbreact';
I'm running it on an older version (4.3.0) with React 16.3.2 and it works great :)

**Comment by nyashafrank** [comment]
Is there a solution to this yet? Still having the same issue with mdbreact 4.8.3

**Comment by Rotarepmi** [comment]
If you have problem with installation please check out our [support forum](https://mdbootstrap.com/support/), or open new issue.

This issue is closed and not tracked.

**Comment by Vahan777** [comment]
У меня та же ошибка. 

ERROR in ./src/components/Boxes.js
Module not found: Error: Can't resolve 'mdbreact' in 'C:\Users\User\Desktop\react2\src\components'
 @ ./src/components/Boxes.js 19:16-35
 @ ./src/components/App.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:9000 webpack/hot/dev-server ./src/index.js

**Comment by ferryal** [comment]
same issue, module not found.
 Could not find a declaration file for module 'mdbreact'. '/Users/feri/Documents/amartha/react-p2p/app/node_modules/mdbreact/dist/mdbreact.js' implicitly has an 'any' type.

**Comment by joelbrice** [comment]
Hello @ferryal !
Here is what solved the problem for me:
Run the following commands:
1. npm install --save mdbreact
2. npm install
If you have any error with Routing, use the following in the index.js;
import { BrowserRouter } from 'react-router-dom';

// Modify the ReactDOM.render() to the below

ReactDOM.render(
<BrowserRouter><App /></BrowserRouter> 
, document.getElementById('root'));

**Comment by PokatilovArt** [comment]
This worked for me

`const mdbreact = require('mdbreact');
const { Button, Collapse } = mdbreact;`

Taken from [StackOverflow](https://stackoverflow.com/questions/41292559/could-not-find-a-declaration-file-for-module-module-name-path-to-module-nam#comment91803917_42505940)

**Comment by Hanumant1987** [comment]
Step 1
npm install --save mdbreact

Step 2

Import style files into the src/index.js before the App.js file import:

[index.js](https://mdbootstrap.com/docs/b4/react/getting-started/installation/#mdb_7ce4d0b28e269b3b8f1c2183c08f29e67b9668a9)
import '@fortawesome/fontawesome-free/css/all.min.css';
import 'bootstrap-css-only/css/bootstrap.min.css';
import 'mdbreact/dist/css/mdb.css';

Step 3

Run your app

[Terminal](https://mdbootstrap.com/docs/b4/react/getting-started/installation/#mdb_364a92f3e32ae31bd4f96cc0722956ff4e1ac151)
npm start
